config/routes.rb
Rails.application.routes.draw do
  root 'recipes#index'

  resources :users

  resources :recipes

  get '/recipes/:id/edit_ingredients', to: 'recipes#edit_ingredients', as: :edit_ingredients
  patch '/recipes/:id', to: 'recipes#update_ingredients'

  get '/recipes/:id/edit_instructions', to: 'recipes#edit_instructions', as: :edit_instructions
  patch '/recipes/:id', to: 'recipes#update_instructions'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :recipe
end

app/models/instruction.rb
class Instruction < ApplicationRecord
  belongs_to :recipe
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user

  has_one_attached :image

  has_many :ingredients, inverse_of: :recipe, dependent: :destroy
  has_many :instructions, inverse_of: :recipe, dependent: :destroy

  accepts_nested_attributes_for :ingredients, allow_destroy: true, reject_if: :all_blank
  accepts_nested_attributes_for :instructions, allow_destroy: true, reject_if: :all_blank

  validates :name, presence: true
  validates :description, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i.freeze

  has_secure_password

  has_many :recipes, dependent: :destroy

  has_one_attached :profile_picture

  before_save :mail_to_downcase

  validates :first_name, presence: true, length: { maximum: 30 }
  validates :last_name, presence: true, length: { maximum: 30 }
  validates :handle_name, presence: true
  validates :mail, presence: true, length: { maximum: 50 },
                   format: { with: VALID_EMAIL_REGEX },
                   uniqueness: true
  validates :password, length: { minimum: 6 }

  def name
    [first_name, last_name].join(' ')
  end

  private

  def mail_to_downcase
    self.mail = mail.downcase
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  before_action :require_login
  before_action :page_title

  private

  def page_title
    @page_title
  end

  def require_login
    unless logged_in?
      flash[:danger] = 'Please sign in to continue'
      redirect_to login_path
    end
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  skip_before_action :require_login, only: %i[index show]
  before_action :set_recipe, except: %i[index new create]
  before_action :check_user, except: %i[index new create show]

  def index
    @recipes = Recipe.all
  end

  def new
    @recipe = Recipe.new
    10.times { @recipe.instructions.build }
    10.times { @recipe.ingredients.build }
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user = current_user

    if @recipe.save
      redirect_to @recipe
    else
      render :new
    end
  end

  def show; end

  def edit
    5.times { @recipe.instructions.build }
    5.times { @recipe.ingredients.build }
  end

  def update
    if @recipe.update(recipe_params)
      redirect_to @recipe
    else
      render :edit
    end
  end

  def destroy
    @recipe.destroy
    redirect_to root_path
  end

  def edit_ingredients
    5.times { @recipe.ingredients.build }
  end

  def update_ingredients
    if @recipe.ingredients.update(other_params)
      redirect_to @recipe
    else
      render :edit_ingredients
    end
  end

  def edit_instructions
    5.times { @recipe.instructions.build }
  end

  def update_instructions
    if @recipe.instructions.update(other_params)
      redirect_to @recipe
    else
      render :edit_instructions
    end
  end

  private

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(:name,
                                   :image,
                                   :description,
                                   instructions_attributes: %i[name id _destroy],
                                   ingredients_attributes: %i[name id _destroy])
  end

  def other_params
    params.permit(:name)
  end

  def check_user
    unless same_user?(@recipe.user)
      flash[:danger] = 'Wrong User'
      redirect_to(root_path) and return
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: %i[new create]

  def new
    redirect_to root_path if logged_in?
  end

  def create
    user = User.find_by(mail: params[:session][:mail].downcase)

    if user&.authenticate(params[:session][:password])
      login(user)
      flash[:success] = "Welcome #{user.name} !!!"
      redirect_to user
    else
      flash.now[:danger] = 'Invalid email or password'
      render :new
    end
  end

  def destroy
    logout
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, except: %i[new create]
  skip_before_action :require_login, only: %i[new create show]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      redirect_to @user
    else
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    unless same_user?(@user)
      flash[:danger] = 'Wrong User!'
      redirect_to(root_path) and return
    end
    if @user.update(user_params)
      redirect_to @user
    else
      render :edit
    end
  end

  def delete
    user.destroy
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :profile_picture, :handle_name, :mail, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def title
    if content_for?(:title)
      content_for :title
    else
      'Food Recipes'
    end
  end
end

app/helpers/instructions_helper.rb
module InstructionsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def login(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def logged_in?
    current_user.present?
  end

  def logout
    session.delete(:user_id)
    @current_user = nil
  end

  def same_user?(other_user)
    current_user == other_user
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_flash.html.erb
<div class="flash">
  <% flash.each do |name, msg| -%>
    <div class="col-5">
      <div class="alert text-center alert-<%= name %>">
        <%= msg %>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer>
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-md-10 mx-auto">
        <ul class="list-inline text-center">
          <li class="list-inline-item">
            <a href="#">
              <%= link_to "https://github.com/ipetrovski3" do %>
                <span class="fa-stack fa-lg">
                  <i class="fas fa-circle fa-stack-2x"></i>
                  <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                </span>
              <% end %>
            </li>
          </ul>
          <p class="copyright text-muted">Copyright © Igor Petrovski 2020</p>
          <p class="copyright text-muted">ipetrovski3@gmail.com</p>
        </div>
      </div>
    </div>
  </footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light" id="mainNav">
  <div class="container">
    <%= link_to 'All Recipes', root_path, class:"navbar-brand" %>
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      Menu
      <i class="fas fa-bars"></i>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <% if logged_in? %>
          <li class="nav-item">
            <%= link_to 'New Recipe', new_recipe_path, class:'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'My Profile', user_path(current_user), class:'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'logout', logout_path, method: :delete, class:'nav-link' %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to 'login', login_path, class:'nav-link' %>
          </li>
          <li class="nav-item">
            <%= link_to 'Register', new_user_path, class:'nav-link' %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= favicon_link_tag asset_path('ico.png') %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/flash' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/recipes/_form.html.erb
<div class="container form-recipes">
  <div class="col-4 col-md-5 mx-auto">
    <div class="post-heading">
      <h1><%= title %> Recipe</h1>
    </div>
    <%= form_with model: @recipe, local: true  do |f| %>
      <div class="form-group">
        <%= f.label :name, class:"label"%>
        <%= f.text_field :name, class:"form-control" %>
          <% @recipe.errors.full_messages_for(:name).each do |msg| if @recipe.errors.any? %>
            <small class="form-text text-danger"><%= msg %> </small>
          <% end %>
          <% end %>
      </div>
      <div class="form-group">
        <%= f.label :image, class:"label" %>
        <%= f.file_field :image, class:"form-control-file" %>
          <% @recipe.errors.full_messages_for(:image).each do |msg| if @recipe.errors.any? %>
            <small class="form-text text-danger"><%= msg %> </small>
          <% end %>
          <% end %>
      </div>
      <div class="form-group">
        <%= f.label :description, class:"label"%>
        <%= f.text_area :description, class:"form-control" %>
          <% @recipe.errors.full_messages_for(:description).each do |msg| if @recipe.errors.any? %>
            <small class="form-text text-danger"><%= msg %> </small>
          <% end %>
          <% end %>
      </div>
      <p>Preparations order:</p>
      <%= f.fields_for :instructions do |instruction| %>
        <%= instruction.text_field :name %>
        <%= instruction.check_box :_destroy %> Delete
      <% end %>
      <p>Ingredients:</p>
      <%= f.fields_for :ingredients do |ingredient| %>
        <%= ingredient.text_field :name %>
        <%= ingredient.check_box :_destroy %> Delete
      <% end %>
      <div class="form-group">
        <%= f.submit submit, class:"btn btn-primary btn-block" %>
        <%= link_to 'Cancel', root_path, class:"btn btn-danger btn-block" %>
      </div>
    <% end %>
  </div>
</div>

app/views/recipes/_recipe.html.erb
<div class="col-lg-4 col-md-6 mb-4">
  <div class="card h-100 mainr">
    <%= link_to image_tag(recipe.image, class: "fit-image"), recipe_path(recipe) if recipe.image.attached? %>
    <%= link_to recipe_path(recipe) do %>
      <div class="card-body">
        <h4 class="card-title">
          <%= recipe.name %>
        </h4>
        <p>Description:
          <%= (recipe.description).truncate(50) %></p>
      </div>
    <% end %>
    <%= link_to recipe_path(recipe) do %>
      <div class="card-footer">
        <small class="text-muted"><%= "Created at: #{recipe.created_at.strftime("%d.%m.%Y, %H:%M")} | by: #{recipe.user.name}"%></small>
      </div>
    <% end %>
  </div>
</div>

app/views/recipes/edit.html.erb
<%= render 'form', submit:"Edit Recipe", title:"Edit" %>

app/views/recipes/edit_ingredients.html.erb
<div class="container form-recipes">
  <div class="col-4 col-md-5 mx-auto">
    <%= form_with model: @recipe, local: true  do |f| %>
      <p>Ingredients:</p>
      <%= f.fields_for :ingredients do |ingredient| %>
        <%= ingredient.text_field :name %>
        <%= ingredient.check_box :_destroy %> Delete
      <% end %>
      <div class="form-group">
        <%= f.submit "Edit", class:"btn btn-primary btn-block" %>
        <%= link_to 'Cancel', root_path, class:"btn btn-danger btn-block" %>
      </div>
    <% end %>
  </div>
</div>

app/views/recipes/edit_instructions.html.erb
<div class="container form-recipes">
  <div class="col-4 col-md-5 mx-auto">
    <%= form_with model: @recipe, local: true  do |f| %>
      <p>Instructions:</p>
      <%= f.fields_for :instructions do |instruction| %>
        <%= instruction.text_field :name %>
        <%= instruction.check_box :_destroy %> Delete
      <% end %>
      <div class="form-group">
        <%= f.submit "Edit", class:"btn btn-primary btn-block" %>
        <%= link_to 'Cancel', root_path, class:"btn btn-danger btn-block" %>
      </div>
    <% end %>
  </div>
</div>

app/views/recipes/index.html.erb
<div class="home-page">
  <div class="container">
    <div class="row">
      <div class="col-lg-6 col-md-8 mx-auto">
        <div class="site-heading">
          <h1><strong>Food Recipes<strong></h1>
          <span class="subheading">Don't visit this page when you are hungry!</span>
        </div>
      </div>
      <div class="row">
        <%= render @recipes %>
      </div>
    </div>
  </div>
</div>

app/views/recipes/new.html.erb
<%= render 'form', submit:"Create", title:"Create New" %>

app/views/recipes/show.html.erb
<div class="container-fluid recimg" style="background-image: url(<%= rails_blob_url(@recipe.image) if @recipe.image.present? %>)">
  <div class="row">
    <div class="col-lg-4 col-md-6 mb-4">
      <div class="card h-100 rec">
        <div class="card-body">
          <h2 class="card-title text-center">
            <strong><%= @recipe.name %></strong>
          </h4>
          <strong>Description:</strong>
          <p> <%= @recipe.description %> </p>
          <p>
            <p> Instructions:
              <ol class="rectangle-list"> <% @recipe.instructions.each do |instruction| %></p>
                <li><%= link_to instruction.name, user_path(@recipe.user) %></li>
              <% end %>
            </ol>
            <%= link_to 'Edit Instructions', edit_instructions_path, class:'btn btn-secondary' if same_user?(@recipe.user) %>
          </p>
          <p class="card-text"> Ingredients:</p>
          <% @recipe.ingredients.each do |ingredient| %>
            <ul><%= ingredient.name %></ul>
          <% end %>
          <%=  link_to 'Edit Ingredients', edit_ingredients_path, class:'btn btn-secondary' if same_user?(@recipe.user) %>
        </div>
        <div class="card-footer">
          <small class="text-muted"><%= "Created at: #{@recipe.created_at.strftime("%d.%m.%Y, %H:%M")} "%></small>
          <% if same_user?(@recipe.user) %>
            <div class="btn-group ml-5">
              <%= link_to 'Edit Recipe', edit_recipe_path(@recipe), class:'btn btn-secondary' %>
              <%= link_to 'Delete Recipe', recipe_path(@recipe), method: :delete, class:'btn btn-secondary' %>
            <% else %>
              <%= link_to "View #{@recipe.user.first_name} Profile Page", user_path(@recipe.user), class:'btn btn-secondary ml-1' %>
              <%= link_to 'Back', root_path, class:'btn btn-secondary' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>
<% content_for :title do  %>
  <% "Recipe - #{@recipe.name}" %>
<% end %>

app/views/users/_form.html.erb
<div class="page-wrapper bg-dark p-t-100">
  <div class="wrapper wrapper--w900">
    <div class="card card-6">
      <div class="signup-form">
        <h2><%= title %></h2>
        <p class="hint-text"><%= subtitle %></p>
        <%= form_with model: @user, local: true do |f| %>
          <div class="form-group">
            <%= f.text_field :first_name, class:"form-control", placeholder:"First Name" %>
              <% @user.errors.full_messages_for(:first_name).each do |msg| if @user.errors.any? %>
                <small class="form-text text-danger"><%= msg %> </small>
              <% end %>
              <% end %>
            <%= f.text_field :last_name, class:"form-control", placeholder:"Last Name" %>
              <% @user.errors.full_messages_for(:last_name).each do |msg| if @user.errors.any? %>
                <small class="form-text text-danger"><%= msg %> </small>
              <% end %>
              <% end %>
          </div>
          <div class="form-group">
            <%= f.text_field :handle_name, class:"form-control", placeholder:"Nickname" %>
              <% @user.errors.full_messages_for(:handle_name).each do |msg| if @user.errors.any? %>
                <small class="form-text text-danger"><%= msg %> </small>
            <% end %>
            <% end %>
          </div>
          <div class="form-group">
            <%= f.label :profile_picture, class:'label' %>
            <%= f.file_field :profile_picture, class:"form-control-file" %>
               <% @user.errors.full_messages_for(:profile_picture).each do |msg| if @user.errors.any? %>
                <small class="form-text text-danger"><%= msg %> </small>
            <% end %>
            <% end %>
          </div>
          <div class="form-group">
            <%= f.email_field :mail, class:"form-control", placeholder:"Email" %>
               <% @user.errors.full_messages_for(:mail).each do |msg| if @user.errors.any? %>
                <small class="form-text text-danger"><%= msg %> </small>
            <% end %>
            <% end %>
          </div>
          <div class="form-group">
            <%= f.password_field :password, class:"form-control", placeholder:"Password" %>
              <% @user.errors.full_messages_for(:password).each do |msg| if @user.errors.any? %>
               <small class="form-text text-danger"><%= msg %> </small>
              <% end %>
              <% end %>
          </div>
          <div class="form-group">
            <%= f.password_field :password_confirmation, class:"form-control", placeholder:"Confirm your password" %>
              <% @user.errors.full_messages_for(:password_confirmation).each do |msg| if @user.errors.any? %>
               <small class="form-text text-danger"><%= msg %> </small>
            <% end %>
            <% end %>
          </div>
          <div class="form-group">
            <%= f.submit submit, class:"btn btn-primary btn-lg btn-block" %>
          </div>
        <% end %>
        <div class="text-center"> Already have an account? | <strong><%= link_to 'Login', login_path, class:"log" %></strong> </div>
      </div>
    </div>
  </div>
  <br>

app/views/users/edit.html.erb
<%= render 'form', title:"Edit Account", subtitle:"Edit your account information.", submit:"Edit Account" %>

app/views/users/new.html.erb
<%= render 'form', title:"Register", subtitle:"Create your account. It's free and only takes a minute", submit:"Register Now" %>

app/views/users/show.html.erb
<div class="container user">
  <div class="view-account">
    <section class="module">
      <div class="module-inner">
        <div class="side-bar">
          <div class="user-info">
           <% if @user.profile_picture.present? %>
            <%= image_tag @user.profile_picture, class:'img-profile' %>
          <% else %>
            <img class="img-profile img-circle img-responsive center-block" src="https://bootdey.com/img/Content/avatar/avatar6.png">
          <% end %>
            <ul class="meta list list-unstyled">
              <li class="name">Full Name: <strong><%= @user.name %></strong></li>
              <li class="name">Nickname: <strong><%= @user.handle_name %></strong></li>
              <li class="email">Email: <strong><%= @user.mail %></strong></li>
              <li class="activity"> Recipes: <strong><%= @user.recipes.count %></strong></li>
            </ul>
          </div>
          <% if same_user?(@user) %>
            <div class="btn-group ml-2">
             <%= link_to 'New Recipe', new_recipe_path, class:'btn btn-primary' %>
             <%= link_to 'Edit Profile', edit_user_path, class:'btn btn-primary' %>
            </div>
          <% end %>
        </div>
        <div class="content-panel">
          <div class="content-header-wrapper">
            <% if same_user?(@user) %>
              <h2 class="title"><%= "My Recipes:" %></h2>
            <% else %>
              <h2 class="title"><%= "#{@user.name} Recipes:" %></h2>
            <% end %>
          </div>
          <div class="drive-wrapper drive-list-view">
            <div class="table-responsive drive-items-table-wrapper">
              <table class="table">
                <% if @user.recipes.any? %>
                  <tbody>
                    <% @user.recipes.each do |r| %>
                      <tr>
                        <td><%= link_to r.name, recipe_path(r) %></td>
                      </tr>
                    <% end %>
                  </tbody>
                <% end %>
              </table>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
</div>
<% content_for :title do  %>
  <% "#{@user.name} profle" %>
<% end %>